name: dbt

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build_manifest:
    runs-on: self-hosted
    steps:
      - name: Скачиваем код
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Устанавливаем Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Устанавливаем зависимости python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Устанавливаем зависимости dbt
        run: |
          cd dbt/hw1
          dbt deps

      - name: Генерируем manifest
        run: |
          cd dbt/hw1
          dbt compile

      - name: Сохраняем manifest в artifact
        run: |
          cd dbt/hw1
          mkdir -p artifacts/dev
          cp target/manifest.json artifacts/dev/manifest.json

      - name: Upload manifest
        uses: actions/upload-artifact@v4
        with:
          name: dbt-dev-manifest
          path: dbt/hw1/artifacts/dev/manifest.json
          retention-days: 1  # храним недолго

  check_is_valid:
    runs-on: self-hosted
    env:
      GITHUB_USER: ${{ github.actor }}
    needs: build_manifest
    steps:
      - name: Скачиваем код
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Устанавливаем Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Устанавливаем зависимости python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Устанавливаем зависимости dbt
        run: |
          cd dbt/hw1
          dbt deps

      - name: Загружаем manifest artifact
        uses: actions/download-artifact@v4
        with:
          name: dbt-dev-manifest
          path: dbt/hw1/artifacts/dev

      - name: Проверка SQL и Jinja синтаксиса
        run: |
          cd dbt/hw1
          dbt parse

      - name: Тестируем измененные модели
        run: |
          cd dbt/hw1
          dbt test --select "state:modified+" --defer --state ./artifacts/dev
       # state:modified+ = все что изменилось плюс зависимости
       # --defer все остальное сравниваем со --state artifacts/dev с последним запуском

      - name: Запуск измененной модели
        run: |
          cd dbt/hw1
          dbt run --target ci --select "state:modified+" --defer --state ./artifacts/dev

       # --target ci = целевая система загрузки из ~/.dbt/profiles.yml